central:
  hostname: "dcra.railway.medicaldataworks.nl"
  port: 443


station:
  environment-variables:
    #No dashes allowed in environment variables.
    sparql_url: "http://host.docker.internal:8888"
    postgres_docker_database: "postgres"

server:
  port: 10080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://dcra-keycloak.railway.medicaldataworks.nl/auth/realms/railway/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: timh
            client-secret: "5b2a6ee7-b9c4-4922-ad17-846258c7491e"
            authorization-grant-type: client_credentials

