logging:
  level:
    root: INFO
    nl.medicaldataworks: DEBUG
  #    org.springframework.web: DEBUG
  file:
    name: station.log

central:
  hostname: "dcra.railway.medicaldataworks.nl"
  port: 443


station:
  enable-audit: true
  environment-variables:
    #No dashes allowed in environment variables.
    sparql_url: "http://host.docker.internal:8888"
    postgres_docker_database: "postgres"

server:
  port: 10080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://dcra-keycloak.railway.medicaldataworks.nl/auth/realms/railway/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: timh
            client-secret: "370fd4da-f8bc-4694-9267-d10d392a2bfe"
            authorization-grant-type: client_credentials

