central:
  hostname: "localhost"
  port: 8080
server:
  port: 10080
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9080/oauth/token
        registration:
          keycloak:
            client-id: "tims-client"
            client-secret: "7796af40-93ff-442c-b4ad-e929dcad02a7"
            authorization-grant-type: client_credentials
