central:
  hostname: "localhost"
  port: 8080

docker-registry:
  username: 
  password: 

server:
  port: 10080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:9080/auth/realms/railway/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: testclient
            client-secret: "fe95901a-a153-47db-a70c-0aaba4de1cf3"
            authorization-grant-type: client_credentials

